name: Update 更新

on:
  schedule:
    - cron: '37 10 */3 * *' # 每12小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:

  update-ip-list:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas

    - name: Make script executable
      run: chmod +x CloudflareST

    - name: hhhh
      run: cat ./ip1.txt

    - name: 测速
      env:
        TEST_URL: ${{ secrets.TEST_URL }}  # 如果是敏感数据，使用 secrets.TEST_URL
      run: |
        set -e
        ./CloudflareST -f ./ip1.txt -t 8 -sl 1 -n 600 -dn 15 -dt 10 -tp 8443 -tlr 0 -url $TEST_URL -o HKG.csv
        python xn.py

    - name: Commit changes to current repository (update1)
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        if [ -n "$(git status --porcelain)" ]; then
          git add ivv.txt valid_ips.txt
          git commit -m "update gengxin"
          git push --force origin main
        else
          echo "No changes detected in update1, skipping commit."
        fi


    - name: Clean up Workflow Runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
         #token: ${{ secrets.GITHUB_TOKEN }}
         token: ${{ secrets.PAT_TOKEN }}
         repository: ${{ github.repository }}
         retain_days: 1
         keep_minimum_runs: 0
