name: Update 更新

on:
  schedule:
    - cron: '37 10 */5 * *' # 每12小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:

  update-ip-list:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
   

    - name: Make script executable
      run: chmod +x CloudflareST

    - name: 测速
      env:
        TEST_URL: ${{ secrets.TEST_URL }}  # 如果是敏感数据，使用 secrets.TEST_URL
      run: |
        set -e
        ./CloudflareST -f iphome.txt -t 8 -p 0 -sl 1 -n 300 -dn 25 -dt 10 -tp 2087 -tlr 0 -url $TEST_URL -o HKG.csv
            python xn.py



    - name: Upload ivv.txt
      env:
        DOMAIN: ${{ secrets.DOMAIN_TOKEN }}
        TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        FILENAME: ivv.txt
      run: |
        chmod +x upload.sh
        ./upload.sh

    - name: Upload valid_ips.txt
      env:
        DOMAIN: ${{ secrets.DOMAIN_TOKEN }}
        TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        FILENAME: valid_ips.txt
      run: |
        chmod +x upload.sh
        ./upload.sh

    - name: Clean up Workflow Runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
         #token: ${{ secrets.GITHUB_TOKEN }}
         token: ${{ secrets.PAT_TOKEN }}
         
         repository: ${{ github.repository }}
         retain_days: 1
         keep_minimum_runs: 0
