name: Update huoq

on:
  schedule:
    - cron: "37 4 * * *"  # 每10分钟跑一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium 
          pip install requests pandas

      - name: Run script
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          
        run: python huoq.py
     

      - name: Make script executable
        run: chmod +x CloudflareST

      - name: cstest
        env:
         TEST_URL: ${{ secrets.TEST_URL }}  # 如果是敏感数据，使用 secrets.TEST_URL
         CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
         CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
         CF_RECORD_NAME: ${{ secrets.CF_RECORD_NAME }}
        run: |
          set -e
          ./CloudflareST -f ip.txt -t 8 -p 0 -sl 1 -n 300 -dn 8 -dt 10 -tp 2087 -tlr 0 -url $TEST_URL
          
            python huoqdn.py
      - name: Clean up Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
         #token: ${{ secrets.GITHUB_TOKEN }}
         token: ${{ secrets.PAT_TOKEN }}
         
         repository: ${{ github.repository }}
         retain_days: 1
         keep_minimum_runs: 0
