name: Update Telecom IPs

on:
  schedule:
    - cron: "*/10 * * * *"  # 每10分钟跑一次
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install playwright requests
          playwright install chromium

      - name: Run script
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
          CF_RECORD_NAME: ${{ secrets.CF_RECORD_NAME }}
        run: python ad.py
