
name: Update yidong

on:
  schedule:
    - cron: '37 2 * * 3' # 每12小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:

  update-ip-list:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests
  
   

    - name: Make script executable
      run: chmod +x CloudflareST

    - name: cstest
      env:
        TEST_URL: ${{ secrets.TEST_URL }}  # 如果是敏感数据，使用 secrets.TEST_URL
      run: |
        set -e
        ./CloudflareST -f v6.txt -t 8 -p 0 -sl 1 -n 300 -dn 25 -dt 10 -tp 2087 -tlr 0 -url $TEST_URL -o HKG.csv
            python yd.py



    - name: Upload yd.txt
      env:
        DOMAIN: ${{ secrets.DOMAIN_TOKEN }}
        TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        FILENAME: yd.txt
      run: |
        chmod +x uploadyd.sh
        ./uploadyd.sh

    - name: Upload valid_ipsyd.txt
      env:
        DOMAIN: ${{ secrets.DOMAIN_TOKEN }}
        TOKEN: ${{ secrets.UPLOAD_TOKEN }}
        FILENAME: valid_ipsyd.txt
      run: |
        chmod +x uploadyd.sh
        ./uploadyd.sh
    - name: Commit changes
      run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          if [ -n "$(git status --porcelain)" ]; then
            git add valid_ipsyd.txt yd.txt
            git commit -m "Automatic update"
            git push
          else
           echo "No changes detected, skipping commit."
          fi
          
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

    - name: Clean up Workflow Runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
         #token: ${{ secrets.GITHUB_TOKEN }}
         token: ${{ secrets.PAT_TOKEN }}
         
         repository: ${{ github.repository }}
         retain_days: 1
         keep_minimum_runs: 0
